backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - label: "Updates"
        name: "updates"
        file: "content/updates.md"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Updates" }
          - { label: "Body", name: "body", widget: "markdown" }
